spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/magic_post
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080
